# -*- coding: utf-8 -*-
"""Atul.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HwhHU6mjb2nSjWG7SZUg9LJlg36vDMiu

# Project_titanic
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

# %matplotlib inline

"""## Data Operations Task

#### Q. Import the Titianic Dataset and Display the Head of the Dataset
"""

df = pd.read_csv('https://raw.githubusercontent.com/thecodescholar/DA_Python_Jun_21/main/Dataset/titanicDataset.csv')
df.head()



"""#### Q. Show the Statistics of dataframe"""

df.describe()

"""#### Q. Display last 3 columns"""

df[['Age', 'Fare', 'Embarked']]

"""#### Q. Show Unique values in Embarked"""

df.Embarked.unique()

"""## Visualization Task

#### Q. Draw histogram for Age, using Matplotlib
"""

plt.hist(data = df, x = 'Age')

"""#### Q. Draw countplot for Sex, using Seaborn"""

sb.countplot(data = df, x = 'Sex')

"""#### Q. Make a Pie Chart of Corona Cases by taking numbers list as [500000, 1800000, 1200000] and labels list as ["Deaths", "Total Cases", "Cured"]"""

list_ = [500000,1800000, 1200000]
labels_ = ["Deaths","Total Cases", "Cured"]
plt.pie(list_, labels = labels_);

"""### Great Job

## All the Best

# THE CODE SCHOLAR
"""